# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job_one:
    name: Deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 109.30.148.110
          username: pi
          key: ${{ secrets.RPI_VIROFLAY_PRIVATE }}
          port: 4243
          source: "*"
          target: "/home/pi/brawlCoach/"
